application: api-project-292527546411
module: default                 # see https://cloud.google.com/appengine/docs/go/
version: alpha                  # you can run multiple versions of an app and A/B test
runtime: go                     # see https://cloud.google.com/appengine/docs/go/
api_version: go1                # used when appengine supports different go versions
manual_scaling:
  instances: 1

default_expiration: 1d        # for CDN serving of static files (use url versioning if long!)

nobuild_files: vendor/

handlers:
# all the static files that we normally serve ourselves are defined here and Google will handle
# serving them for us from it's own CDN / edge locations. For all the configuration options see:
# https://cloud.google.com/appengine/docs/go/config/appconfig#Go_app_yaml_Static_file_handlers
- url: /
  mime_type: text/html
  static_files: ../dist/index.html
  upload: ../dist/index.html

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: ../dist/static/favicon.ico
  upload: ../dist/static/favicon.ico

- url: /static/js
  mime_type: text/javascript
  static_dir: ../dist/static/js

- url: /static/css
  mime_type: text/css
  static_dir: ../dist/static/css

# finally, we route all other requests to our application. The script name just means "the go app"
- url: /.*
  script: _go_app

skip_files:
  - ^(build)
  - ^(config)
  - ^(node_modules)
  - ^(src)
  - ^(test)
  - ^(vendor)
  - ^(app.yaml)
  - ^(glide.lock)
  - ^(glide.yaml)
  - ^(package.json)
  - ^(README.md)
  - ^(.*/)?\..*$
